### ISSUE TITLE
Loading safetensors quantized model (MPT)

### ISSUE THREAD

**Issue by 1aienthusiast** [0cc4m/hf_bleeding_edge#1]
how do you load the quantized model (MPT) and prompt it? if I use
`model = transformers.AutoModelForCausalLM.from_pretrained('./models/mosaicml_mpt-7b',local_files_only=True, trust_remote_code=True,prefer_safe=True,config=config) `
i get the error
`OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./models/mosaicml_mpt-7b.`
which is understandable because the model is in the safetensors format.
I quantized the model using the following command:
`python3.10 mpt.py --wbits 4 --groupsize 128 --save_safetensors mpt-7b-base-4bit-128g.safetensors <MODEL DIRECTORY> c4`

**Comment by 0cc4m** [comment]
Still working on the support for it. It's 95% done, once it's ready you will be able to load it seamlessly using KoboldAI.

**Comment by 0cc4m** [comment]
Should work now with the latest 4bit Kobold client.
